### ISSUE TITLE
The big To-Do

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#123]
- [ ] Grab checkbox labels from game data  

  Currently, a *Lunar Outpost* will appear as *MoonOutpost*, because that is its ID. The actual button label should be used.

- [ ] Optimize *enabled* checks  

  Currently, some checks (like `!options.auto.build.items[name].enabled`) will be performed after performance-critical calls have been made. This should be avoided.

- [ ] Store checkbox state of main area in save data

  Currently, when you disable the *Building* checkbox and reload the page, the *Building* checkbox is enabled again.

I'll try extra-hard to send PRs for all items on this list myself. I just wanted to keep it here :) And, yes, I'm currently working on a Space patch.

**Comment by cameroncondry** [comment]
Thank you for continuing to update the system. Definitely love that people still find the script useful.

**Comment by oliversalzburg** [comment]
@cameroncondry I find it very useful and I have a lot of fun working on it as well :) I hope I'll find more time to check more points of the list very soon.

BTW, I tested #120 for quite some time now and the only thing I still feel somewhat odd about are Festivals. I feel like they often start when I switch to the City tab. So I fear that they might not be starting when a different tab is focused. In general though, I feel like that patch is a huge performance improvement.

**Comment by Ramdat** [comment]
Can you add an option for more log activity filters? Currently it spams the log with finding astronomical events, getting science from the events and making starcharts. It would also be nice to filter out specific automatic crafts, such as furs -> parchment -> compendium. 

You removed the added CSS for all themes?

**Comment by oliversalzburg** [comment]
@Ramdat The CSS is removed only for the Sleek theme. The CSS is still applied for all of the "classical" themes. Some options also apply to the Sleek theme though. Overall, this change just made KS more compatible with the Sleek theme.

The log is a huge pain IMHO and needs a lot more work. I feel like some filters don't actually work and the filters only appear to hide log messages. The messages are still taking up slots in the log. So the hidden entries still push the interesting log entries out of the log.

**Comment by cameroncondry** [comment]
That is correct about how the log filters work. The script adds a class to the different log items to hide via css. The class could be used instead to simply remove them from the log completely. However, the reason behind hiding them is I originally wanted a way to unhide them, but that is no longer helpful I think since the game has expanded since the log filtering was originally implemented.

**Comment by oliversalzburg** [comment]
I also optimized one `enabled` check in https://github.com/oliversalzburg/cbc-kitten-scientists/tree/feature/stages already. I'll create a PR for that when #127 is merged, as that feature relies on some changes in #127.

**Comment by Ramdat** [comment]
@oliversalzburg The horizontal spacing of the CSS for every theme except Sleek do not work properly for me. It has roughly 400px of blank space on the right side. For reference vanilla has 600px of empty space.

**Comment by oliversalzburg** [comment]
@Ramdat Huh, weird. Please open a separate issue about this and include some screenshots. I'll look into it.

**Comment by GronbergInfo** [comment]
Do KS account for IW mode?

**Comment by cameroncondry** [comment]
Currently there are no specific settings that change functionality for IW mode. You can update the options to work better in IW, like disabling building any type of housing.
